name: flutter_app
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.0
  url_launcher: ^6.0.9
  google_fonts: ^2.1.0
  analyzer: ^1.6.0
  adaptive_theme: ^2.2.0
  intl: ^0.17.0
  page_transition: ^2.0.2
  nylo_framework: ^1.1.0
  nylo_support: ^1.0.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "public/assets/app_icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - public/assets/images/
    - lang/en.json
    - .env

  fonts:
    - family: yekan
      fonts:
        - asset: public/assets/fonts/yekan.ttf
